services:
  unopim-web:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    container_name: unopim-web
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - unopim-mysql
    volumes:
      - unopim-storage:/var/www/html/storage
      - unopim-public-storage:/var/www/html/public/storage

  unopim-q:
    build:
      context: .
      dockerfile: dockerfiles/q.Dockerfile
    container_name: unopim-q
    restart: unless-stopped
    depends_on:
      - unopim-mysql
    volumes:
      - unopim-storage:/var/www/html/storage

  unopim-mysql:
    image: mysql:8
    container_name: unopim-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: unopim
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - unopim-mysql-disk:/var/lib/mysql

  unopim-mailpit:
    image: axllent/mailpit:latest
    container_name: unopim-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"

volumes:
  unopim-mysql-disk: {}
  unopim-storage: {}
  unopim-public-storage: {}
